server:
  port: 8088

spring:
  profiles:
    active: dev # 环境设置

  application:
      name: Customerservice

  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: SH  #集群名称

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.feign_api.Pojo
    configuration:
      mapUnderscoreToCamelCase: true  # ✅ 正确写法，驼峰用小驼峰风格！


  jackson:
    time-zone: America/Los_Angeles
    date-format: yyyy-MM-dd HH:mm:ss

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pizzahut?serverTimezone=America/Los_Angeles&useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: PizzaHutUser
    password: "f25012501"